FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc iproute2 iptables && \
    rm -rf /var/lib/apt/lists/*

# requirements для агента (меньше зависимостей)
RUN pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    httpx \
    "pydantic<2.14" \
    "pydantic-settings<2.14" \
    psutil \
    cryptography

COPY agent.py .

EXPOSE 2095
CMD ["python", "agent.py"]
